server:
  port: 8081

spring:
  application:
    name: spring_ai_demo

  ai:
    #config for persistent chat memory
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    openai:
#      open AI config
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        model: ${OPENAI_MODEL}
#        max-tokens: 25
#        max-completion-tokens: 30

#      GROQ AI config(uses OpenAI dependency)
      api-key: ${GROQ_API_KEY}
      base-url: ${GROQ_BASE_URL}
      chat:
        model: ${GROQ_MODEL}

#    google:
#      genai:
##        api-key: ${GOOGLE_API_KEY}
#        chat:
#          model: ${GOOGLE_AI_MODEL}

#config for persistent chat memory
  datasource:
    url: jdbc:h2:file:./data/db/chatmemory;AUTO_SERVER=TRUE #stores the data in a file, and reads it when server restarts.
    driver-class-name: org.h2.Driver

#enabling logging for Spring AI
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
