package com.ai.demo.controller.advisors;

import org.springframework.ai.chat.client.ChatClientRequest;
import org.springframework.ai.chat.client.ChatClientResponse;
import org.springframework.ai.chat.client.advisor.api.AdvisorChain;
import org.springframework.ai.chat.client.advisor.api.BaseAdvisor;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.model.Generation;

import java.util.List;

public class DisclaimerAdvisor implements BaseAdvisor {

    private final int order;
    private final static String DISCLAIMER = """
    ---
    _This response was generated by AI & may contain inaccuracies._
    """;

    public DisclaimerAdvisor(int order) {
        this.order = order;
    }

    @Override
    public ChatClientRequest before(ChatClientRequest chatClientRequest, AdvisorChain advisorChain) {
        return chatClientRequest;
    }

    @Override
    public ChatClientResponse after(ChatClientResponse chatClientResponse, AdvisorChain advisorChain) {

        ChatResponse chatResponse = chatClientResponse.chatResponse();
        if(chatResponse == null || chatResponse.getResult() == null){
            return chatClientResponse;
        }

        AssistantMessage aiResponse = chatResponse.getResult().getOutput();

        //Adding additional info to the AI response before showing to the user
        AssistantMessage aiResponseWithDisclaimer = AssistantMessage.builder()
                .content(aiResponse.getText() + DISCLAIMER)
                .properties(aiResponse.getMetadata())
                .toolCalls(aiResponse.getToolCalls())
                .media(aiResponse.getMedia())
                .build();

        //setting back  the updated ai response back to ChatResponse.
        Generation updateGeneration = new Generation(aiResponseWithDisclaimer, chatResponse.getResult().getMetadata());
        ChatResponse updatedChatResponse = ChatResponse.builder()
                .from(chatResponse)
                .generations(List.of(updateGeneration))
                .build();

        return chatClientResponse.mutate().chatResponse(updatedChatResponse).build();
    }

    @Override
    public int getOrder() {
        return this.order;
    }
}
